title: Muktakosh
description: Researching and building exponential technologies in an open and sustainable manner
baseurl: ""
url: "https://muktakosh.org"
timezone: Asia/Kolkata
lang: en-GB

contact:
  - twitter: muktakosh
  - facebook: muktakosh
  - github: muktakosh
  - email: info@muktakosh.org

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: blog
    type: pages
  values:
    sectionid: blog

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bower.json

permalink: "blog/:slug"
paginate: 5
paginate_path: "/blog/page/:num"

layouts_dir: _theme/_layouts
data_dir: _theme/_data
includes_dir: _theme/_includes
plugins_dir: _theme/_plugins

sass:
  style: compressed
  load_paths:
    - _theme/_sass
    - _theme/_vendors/foundation-sites/scss
